<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme. 
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */
 
 /* Template Name: Homepage*/

add_filter('genesis_entry_content', 'home_page');

function home_page() {

?>

<p>hometemplate</p>

<?php

}

genesis();
